---
version: 2
jobs:
  build:
    docker:
    - image: suzukishunsuke/hugo-ci:0.1.2
    steps:
    - checkout
    - run: git config user.name "Suzuki Shunsuke"
    - run: git config user.email "suzuki.shunsuke.1989@gmail.com"
    - run: git clone --depth 1 https://github.com/suzuki-shunsuke/tale-hugo themes/tale
    - run: hugo
    - run: cat public/css/style.css
    - run: sh release.sh
workflows:
  version: 2
  build:
    jobs:
    - build:
        filters:
          branches:
            only: source
